### ISSUE TITLE
20% - 40% of images are missing or not downloaded

### ISSUE THREAD

**Issue by glenn-jocher** [harshilpatel312/open-images-downloader#2]
tqdm shows 350 'kitchen knife' images should be downloaded, but only 275 appear in the output folder (21% missing). Similarly only 727 or 1200 'knife' images appear (39% missing)

To reproduce use these arguments:
```
ANNOTATIONS = 'train-annotations-bbox.csv'
OUTPUT_DIR = './output'
OBJECTS = ['kitchen knife']
LABELMAP = 'class-descriptions-boxable.csv'
IMAGES = 'train-images-boxable.csv'
```

**Comment by tohow06** [comment]
In my observation,  tqdm shows 350 'kitchen knife' might mean train-annotations-bbox.csv has 350 rows of kitchen knife 
but some rows are annotated on same pictures

**Comment by glenn-jocher** [comment]
@tohow06 yes this same thing had occurred to me yesterday. I think you are correct, the tqdm number is reflecting the number of instances rather than the number of images.
